spring:
  application:
    name: cli-mini-game

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:file:./data/gamehub;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (??? ? ?????)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    io.yogurt.cli_mini_game: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE